version: '3.7'
services:
  django-tutorial:
    container_name: django-tutorial
    image: fabiiogonzalez8/django:35
    restart: always
    environment:
      ALLOWED_HOSTS: "https://djangodocker.supergallo.es"
      HOST: bd_mariadb_django
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
    ports:
      - 8086:6000
    depends_on:
      - db_django
  db_django:
    container_name: bd_mariadb_django
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django:/var/lib/mysql
volumes:
    mariadb_data_django:
